Основы JS. Примитивные типы данных
js-tasks-ru/js-20210427_stanislav-semenov pull request #2
Opened 2021-05-03 05:59 UTC by StanislavSemenov

Выполнены задачи:
1. sortStrings
2. pick
3. omit
Описание: Применен метод "Object.entries(obj)", тестирование выполнено успешно.

2021-05-03 05:59 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-05-04 09:49 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let newArray = [...arr]
проверьте, здесь точно `let`?

2021-05-04 09:49 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        ? newArray.reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-05-04 09:50 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        for (let key of arrayData) {
Подумайте, может ли как-то упростить код использование метода `includes` 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2021-05-04 09:51 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (let field of fields) {
подумайте, а `field` - это точно `let`?

2021-05-04 09:51 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    const arrayData = [...Object.entries(obj)]
нет необходимости копировать значения `Object.entries` в новый массив

2021-05-04 09:51 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    const newObj = {}
аналогичные замечания как в `pick`

2021-05-04 09:52 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-05-04 10:06 UTC, StanislavSemenov commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let newArray = [...arr]
Технически, будет работать и с let, но это будет плохим тоном и корректнее будет использовать const. Из-за нехватки опыта опасаюсь ошибоб, боэтому более склонялся к let, даже с объектами. Исправил.

2021-05-04 10:19 UTC, StanislavSemenov commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let newArray = [...arr]
Конечно, правильнее писать, const, поскольку ссылка на массив неизменна, меняются только ссылки на его элементы... Насколько данная ошибка считается плохим тоном в проектах и к каким ошибкам может привести?

2021-05-04 12:12 UTC, StanislavSemenov commented on 02-javascript-data-types/2-pick/index.js
> +    for (let field of fields) {
Да, конечно исправил на const. Какие функциональные  риски возможны при использовании let на моем примере или это только хороший тон программирования?

2021-05-04 12:14 UTC, StanislavSemenov commented on 02-javascript-data-types/2-pick/index.js
> +    const arrayData = [...Object.entries(obj)]
согласен, остатки поиска ошибок в тестировании... Вообще удалил переменную arrayData и перенес Object.entries(obj) в условие цикла

2021-05-04 12:20 UTC, StanislavSemenov commented on 02-javascript-data-types/3-omit/index.js
> +    const newObj = {}
Исправил

2021-05-04 12:51 UTC, StanislavSemenov reviewed
Замечания исправлены

2021-05-04 12:51 UTC, StanislavSemenov commented on 02-javascript-data-types/1-sort-strings/index.js
> +        ? newArray.reverse()
исправлено путем замены местами двух сравниваемых значений (a,b) таким образом sort() работает в противоположном направлении (меняется знак-ключь для условия сортировки)

2021-05-06 12:20 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let newArray = [...arr]
это не критичная ошибка, более того часть разработчиков даже за ошибку это не считает, но этот маленький момент может значительно улучшить читабельность кода

2021-05-06 12:21 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (let field of fields) {
`let` можно случайно перетереть, это основная техническая проблема которая может случиться

2021-05-06 12:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +function isEmpty(obj) {
эту функцию можно свести просто к выражению `Object.keys(obj).length`

2021-05-06 12:24 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    else
`else` не нужен, так как первый блок `if` имеет `return` который оборвет выполнение функции

2021-05-06 12:24 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +                for (const key of path.split('.')) {
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-05-06 12:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +        return undefined
мы не работаем с `undefined` напрямую, достаточно просто `return`

2021-05-06 12:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return [...new Set(arr)]
good 👍

2021-05-06 12:25 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-05-06 15:35 UTC, StanislavSemenov commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +        return undefined
Исправлено

2021-05-06 15:35 UTC, StanislavSemenov commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +                for (const key of path.split('.')) {
исправлено

2021-05-06 15:35 UTC, StanislavSemenov commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    else
исправлено

2021-05-06 15:36 UTC, StanislavSemenov commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +function isEmpty(obj) {
исправлено

2021-05-07 18:14 UTC, StanislavSemenov commented
Произвел рефакторинг, спустя два дня решения и оптимизации код оказался до безобразия прост, но это мнение субъективное, с нетерпением жду согласования)

2021-05-10 19:35 UTC, dosandk approved these changes
good 👍  хорошие решения

2021-05-10 19:36 UTC, merged